
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLCER = 7;
  public static final int RESERV_INT = 12;
  public static final int LLAB = 6;
  public static final int ELSE = 2;
  public static final int PLUS = 16;
  public static final int INT = 13;
  public static final int CORAB = 8;
  public static final int WHILE = 10;
  public static final int RETURN = 17;
  public static final int CORCER = 9;
  public static final int IF = 3;
  public static final int ID = 11;
  public static final int EOF = 0;
  public static final int PARENIZQ = 4;
  public static final int error = 1;
  public static final int ASSIG = 15;
  public static final int PARENDER = 5;
  public static final int PUNTOCOMA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ELSE",
  "IF",
  "PARENIZQ",
  "PARENDER",
  "LLAB",
  "LLCER",
  "CORAB",
  "CORCER",
  "WHILE",
  "ID",
  "RESERV_INT",
  "INT",
  "PUNTOCOMA",
  "ASSIG",
  "PLUS",
  "RETURN"
  };
}

