
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 30 00:21:24 ART 2019
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 10;
  public static final int WHILE = 8;
  public static final int INTEGER = 15;
  public static final int LLAB = 6;
  public static final int ASSIG = 12;
  public static final int PLUS = 13;
  public static final int EOF = 0;
  public static final int IF = 3;
  public static final int LLCER = 7;
  public static final int PARENIZQ = 4;
  public static final int ID = 9;
  public static final int ELSE = 2;
  public static final int error = 1;
  public static final int PUNTOCOMA = 11;
  public static final int PARENDER = 5;
  public static final int RETURN = 14;
}

